# Generated by Django 3.0.2 on 2020-04-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('search_kobo', 'Can Search Kobo'), ('search_google', 'Can Search Google'), ('search_livraria', 'Can Search Livraria'), ('search_scribd', 'Can Search Scribd'), ('search_teststore', 'Can Search Test Book Store'), ('search_audiobooks', 'Can Search Audio Books'))},
        ),
    ]
