# Generated by Django 3.0.5 on 2020-04-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_group_contact_user'),
        ('clients', '0004_auto_20200410_0444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
